<html><head></head><body>

	<div style="text-align: center; height: 400px; vertical-align: middle; padding-top: 140px;">
		<div style="font-family: Arial; font-size: 11px; margin-bottom: 20px;"><?php echo $this->__('Payment successfully received.') ?></div>
		<img style="border: 0px;" src="<?php echo $this->getSkinUrl('images/auriga/loading.gif') ?>">
  </div>

    <script language="javascript">
        this.parent.parent.window.location = '<?php echo Mage::getUrl('checkout/onepage/success'); ?>';
    </script>

</body></html>
