<!--
/**
 * Klarna
 * JavaScript includes for OneStepCheckout
*/
-->
<script src="//static.klarna.com/external/kitt/toc/v1.1/js/klarna.terms.min.js" type="text/javascript" charset="utf-8"></script>
<script src="//static.klarna.com/external/kitt/legacy/klarnaConsentNew.js" type="text/javascript" charset="utf-8"></script>
<script src="//static.klarna.com/external/kitt/letop/v1.0/js/klarna.letop.js" type="text/javascript" charset="utf-8"></script>
