<script type="text/javascript">
    var canAddToCartExist = false;
    var canAddToCartNew = false;
    var productAddToCartForm = new VarienForm('product_addtocart_form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {

            var is_exist = jQuery('#radioActivationTypeExist');
            if (is_exist.is(":checked")) {
                jQuery("#newnumber").remove();
            }
            var is_new = jQuery('#radioActivationTypeNew');
            if (is_new.is(":checked")) {
                jQuery("#numberfield").remove();
            }

            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }

            this.form.submit();

            if (button && button != 'undefined') {
                button.disabled = true;
            }
            jQuery('#product_addtocart_form .validation-advice:visible').closest('.control-group').removeClass('error');
        }
    }.bind(productAddToCartForm);
</script>

<script type="text/javascript">
    function sendsms()
    {
        var field = jQuery('#numberfield');
        var cont = jQuery('.telephone-number');
        var subId = jQuery('#product_addtocart_form input[id*="options_"]:checked').attr('subid');
        var errorContainer = jQuery('#advice-validate-phonenumber-numberfield');
        var numberErrorMsg = '<?php echo $this->__('Du glömde att fylla i ditt mobilnummer!');?>';

        var numberfield = field.val();
        if(numberfield.length !== 0 && numberfield !== field.attr('placeholder')){
            numberfield = numberfield.replace(/[-\s]/g,"");
            numberfield = numberfield.replace(/\s+/g, "");
            var phoneRegExp = /^[0-3]7[\d]{8}$/;
            if (phoneRegExp.test(numberfield) && (numberfield.length == 10)) {
                jQuery.post('<?php echo $this->getUrl('sS4Integration/index/sendsms'); ?>', {number:numberfield, subid:subId},
                    function(data) {
                        if(data == 'error'){
                            cont.addClass('error');
                            errorContainer.show().css('opacity',100);
                            jQuery('.code-number').css("display", "none");
                            errorContainer.html('<?php echo $this->__('Detta telefonnummer existerar redan för en annan telefon i varukorgen') ?>')
                        } else if (data) {
                            cont.removeClass('error');
                            jQuery('.code-number').css("display", "inline");
                            errorContainer.html('<?php echo $this->__('Ett sms har skickats iväg') ?>')
                        } else {
                            cont.addClass('error');
                            errorContainer.html('<?php echo $this->__('Du har skrivit in ett ogiltigt mobilnummer! Ex. 070-000 00 00') ?>')
                        }
                    },
                    'json'
                );
            } else {
                cont.addClass('error');
                errorContainer.html('<?php echo $this->__('Du har skrivit in ett ogiltigt mobilnummer! Ex. 070-000 00 00') ?>')
            }
        } else {
            if(!jQuery('*:contains(" ' + numberErrorMsg + '")').length){
                cont.addClass('error');
                errorContainer.html(numberErrorMsg);
            }
        }
        return false;
    }

    function validatenumber()
    {
        var field = jQuery('#numberfield');
        var cont = jQuery('.telephone-number');
        var subId = jQuery('#product_addtocart_form input[id*="options_"]:checked').attr('subid');
        var errorContainer = jQuery('#advice-validate-phonenumber-numberfield');
        var numberErrorMsg = '<?php echo $this->__('Du glömde att fylla i ditt mobilnummer!');?>';

        var numberfield = field.val();
        if(numberfield.length !== 0 && numberfield !== field.attr('placeholder')){
            numberfield = numberfield.replace(/[-\s]/g,"");
            numberfield = numberfield.replace(/\s+/g, "");
            var phoneRegExp = /^[0-3]7[\d]{8}$/;
            if (phoneRegExp.test(numberfield) && (numberfield.length == 10)) {
                jQuery.post('<?php echo $this->getUrl('sS4Integration/index/validatenumber'); ?>', {number:numberfield, subid:subId},
                    function(data) {
                        if(data.result == 'Ok') {
                            errorContainer.html(data.type);
                            jQuery('#addToCartButton').removeAttr('disabled');
                        } else {
                            cont.addClass('error');
                            errorContainer.html('<?php echo $this->__('Du har skrivit in ett ogiltigt mobilnummer! Ex. 070-000 00 00') ?>');
                        }
                    },
                    'json'
                );
            } else {
                cont.addClass('error');
                errorContainer.html('<?php echo $this->__('Du har skrivit in ett ogiltigt mobilnummer! Ex. 070-000 00 00') ?>')
            }
        } else {
            if(!jQuery('*:contains(" ' + numberErrorMsg + '")').length){
                cont.addClass('error');
                errorContainer.html(numberErrorMsg);
            }
        }
        return false;
    }

    function validatecode()
    {
        var numberfield = jQuery('#numberfield').val();
        var codefield = jQuery('#codefield').val();
        var cont = jQuery('.code-number');
        var errorContainer = jQuery('.code-number .row-fluid .help-block:first');
        var smsErrorMsg = '<?php echo $this->__('Du har glömt att skriva i SMS-koden!') ?>';
        var subId = jQuery('#product_addtocart_form input[id*="options_"]:checked').attr('subid');
        var nosfa = false;
        if (jQuery('#prepaid').hasClass('active')) {
            var period = jQuery('#prepaid').find(":checked");
            if(period.attr('bind_period') == 0) {
                nosfa = true;
            }
        }

        if (codefield.length == 4) {
            jQuery.post('<?php echo $this->getUrl('sS4Integration/index/validatecode'); ?>', {number:numberfield, code:codefield, subid:subId},
                function(data) {
                    if (data.error) {
                        cont.addClass('error');
                        errorContainer.html(data.error);
                        jQuery('.container-nano-sim-type').data('result',0).hide();
                    } else {
                        if (data.result) {
                            if (data.type == "NONE" && nosfa) {
                                jQuery('.telephone-number').addClass('error');
                                errorContainer.html("Tyvärr kan inte valt nummer flyttas");
                                jQuery('#addToCartButton').attr('disabled', 'disabled');
                            } else {
                                cont.removeClass('error');
                                errorContainer.html(data.result);
                                canAddToCartExist = true;
                                if (data.type.toLowerCase() == 'prolong' || (data.type.toLowerCase() == "none" && !nosfa)) {
                                    jQuery('.container-nano-sim-type').data('result',1).show();
                                }
                                jQuery('#addToCartButton').removeAttr('disabled');
                            }
                        }
                    }
                },
                'json'
            );
        } else {
            if(!jQuery('*:contains(" ' + smsErrorMsg + '")').length){
                jQuery(".validation-advice").hide();
                cont.addClass('error');
                errorContainer.html(smsErrorMsg);
            }
        }
        return false;
    }

    <?php if (!$this->getIsDongle()): ?>
        jQuery('#addToCartButton').attr('disabled', 'disabled');
    <?php endif; ?>

    jQuery('[name=radioActivationType]').change(function(){
        if (jQuery('#radioActivationTypeExist').is(':checked') && !canAddToCartExist) {
            jQuery('#addToCartButton').attr('disabled', 'disabled');
        } else if (jQuery('#radioActivationTypeExist').is(':checked') && canAddToCartExist) {
            jQuery('#addToCartButton').removeAttr('disabled');
        }
        if(jQuery('#radioActivationTypeNew').is(':checked') && !canAddToCartNew) {
            jQuery('#addToCartButton').attr('disabled', 'disabled');
        } else if (jQuery('#radioActivationTypeNew').is(':checked') && canAddToCartNew) {
            jQuery('#addToCartButton').removeAttr('disabled');

        }
    });
    jQuery('input[name="radioActivationType"]').change(function(e){
        if (jQuery(this).is('#radioActivationTypeNew')) {
            if (!jQuery('a[data-toggle="tab"][href="#prepaid"]').parent().hasClass('active')) {
                jQuery('#ActivationTypeNew').show();
                try { //selectorize doesn't work in IE and breaks
                    //jQuery('#newnumber').selectorize();
                } catch(err) {};

            }
            jQuery('#ActivationTypeExist').hide();
            jQuery('.container-nano-sim-type').hide();
        } else if (jQuery(this).attr('id') == 'radioActivationTypeExist') {
            jQuery('#ActivationTypeExist').show();
            jQuery('#ActivationTypeNew').hide();
            if (jQuery('.container-nano-sim-type').data('result') == 1) {
                jQuery('.container-nano-sim-type').show();
            }
        }
    });
    
    // Segment Pixel - Tele4G - Postpaid
    var urlPixelPost = '<?php echo Tele4G_Common_Helper_Data::SEGMENT_PIXEL_COMVIQ_POSTPAID; ?>';
    // Segment Pixel - Tele4G - Prepaid
    var urlPixelPre = '<?php echo Tele4G_Common_Helper_Data::SEGMENT_PIXEL_COMVIQ_PREPAID; ?>';
    var segmentPixelHTML = '<img src="#SRC#" id="segment_pixel" width="1" height="1" />';

    //Init custom select UI on Prepaid tab when it shown
    tele4g.eventManager.bind('subscriptionTypeChanged', function(event){
        if (event.data == 'prepaid') {
            jQuery('#minTotalCostContainer').css('visibility', 'hidden');
            jQuery('#product_addtocart_form input[id*="options_"]').each(function(index, element) {
                jQuery(element)
                    .removeAttr('checked')
                    .parent('.tele4g-radio').removeClass('selected');
            });
            jQuery('#'+radio_pre)
                .attr('checked', 'checked')
                .parent('.tele4g-radio').addClass('selected');
            jQuery('#ActivationTypeNew').hide();
            jQuery('#newnumber option:selected').removeAttr('selected');
            jQuery('#newnumber option:first').attr('selected','selected');
            jQuery('#segment_pixel').remove();
            jQuery('body').append(segmentPixelHTML.replace('#SRC#',urlPixelPre + '&' + new Date().getTime()));
        }
        if (event.data == 'postpaid') {
            jQuery('#minTotalCostContainer').css('visibility', 'visible');
            loadBindPeriodsPost();
            jQuery('#product_addtocart_form input[id*="options_"]').each(function(index, element) {
                jQuery(element)
                    .removeAttr('checked')
                    .parent('.tele4g-radio').removeClass('selected');
            });
            jQuery('#'+radio_post)
                .attr('checked', 'checked')
                .parent('.tele4g-radio').addClass('selected');
            if (jQuery('#radioActivationTypeNew:checked').length) {
                jQuery('#ActivationTypeNew').show();
                var selectNumber = jQuery('#newnumber').parent('.selectorize').find('.select .selected').text();
                jQuery('#newnumber option:contains('+selectNumber+')').attr('selected','selected');
            }
            jQuery('#segment_pixel').remove();
            jQuery('body').append(segmentPixelHTML.replace('#SRC#',urlPixelPost + '&' + new Date().getTime()));
        }
    }, 'namespace');

    if (jQuery('#prepaid').hasClass('active'))
        jQuery('#minTotalCostContainer').css('visibility', 'hidden');


    jQuery('#ajax_loader').show();
    jQuery('#newnumber').hide();
    jQuery.post('<?php echo $this->getUrl('sS4Integration/index/availablePhoneNumbers'); ?>',
        function(data) {
            if (data.status == "OK") {
                jQuery('#ajax_loader').hide();
                jQuery.each(data.response, function(key, value) {
                    jQuery('#newnumber')
                        .append(jQuery('<option></option>')
                        .attr("value",value)
                        .text(value));
                    if (key == 0) {
                        jQuery('#newnumber option:eq(0)').attr('selected', 'selected');
                    }
                });
                jQuery('#newnumber').selectorize();
                if(jQuery('#radioActivationTypeNew').is(':checked')) {
                    jQuery('#addToCartButton').removeAttr('disabled');
                }
                canAddToCartNew = true;
            } else {
                jQuery('#ajax_loader').hide();
                jQuery('#ActivationTypeNew').append(data.error_message);
            }
        },
        'json'
    );
    jQuery(document).ready(function() {
        jQuery('#confirm_number').attr('disabled', 'disabled');
        jQuery.post('<?php echo $this->getUrl('tele4G_nocache/'); ?>',
            function(data) {
                jQuery('#confirm_number').removeAttr('disabled');
                if (data && data.action) {
                    jQuery('#confirm_number').removeAttr('onclick');
                    jQuery('#confirm_number').attr('onclick', data.action);
                }
            },
            'json'
        );
    });
</script>

<script>
    jQuery('.show-full-spec').click(function(e){
        e.preventDefault();
        jQuery(this).toggleClass('collapsed');
        jQuery('#article-info').slideToggle();
    });
</script>