<?php
/**
 * @category    design
 * @package     tele4G_default
 */
?>
<?php
/**
 * AllProducrs view template
 *
 * @see Tele4G_Catalog_Block_AllProducts_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = '') { //= $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->htmlEscape($_category->getName()).'" title="'.$this->htmlEscape($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div id="breadcrumbs" class="container">
    <ul class="breadcrumb">
        <li><a href="<?php echo Mage::getStoreConfig("tele4G/variables/tele4G_main_page")?>"><?php echo $this->__('Hem') ?></a> <span class="divider">›</span></li>
        <li class="active"><?php echo $this->__('Mobiltelefoner') ?></li>
    </ul>
</div>
<div class="container web-shop">
    <h1><?php echo $this->__('Mobiltelefoner') ?></h1>
    <?php if($_imgUrl): ?>
        <?php echo $_imgHtml ?>
    <?php endif; ?>

    <?php if($_description = ''): //=$this->getCurrentCategory()->getDescription()): ?>
        <div class="category-description std">
            <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
        </div>
    <?php endif; ?>

    <?php /*if($this->isContentMode()): ?>
        <?php echo $this->getCmsBlockHtml() ?>

    <?php elseif($this->isMixedMode()): ?>
        <?php echo $this->getCmsBlockHtml() ?>
        <?php echo $this->getProductListHtml() ?>

    <?php else: ?>
        <?php echo $this->getProductListHtml() ?>
    <?php endif; */?>
    <?php echo $this->getProductListHtml() ?>
</div>
