<html><head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
</head><body>

  <div style="text-align: center; height: 400px; vertical-align: middle; padding-top: 140px;">
		<div style="font-family: Arial; font-size: 11px; margin-bottom: 20px;"><?php echo $this->__('You will be redirected to Auriga in a few seconds.') ?></div>
		<img style="border: 0px;" src="<?php echo $this->getSkinUrl('images/lightbox/load.gif') ?>">
  </div>

<?php
	$aurigamodel = $this->getAuriga();
	$formfields =$aurigamodel->getCheckoutFormFields(); 
	// Add everything needed for auriga to the form.
	$cgi = ''; //'?oid=' . $formfields['orderid'];
	echo '<form action="' . $aurigamodel->getUrl() . $cgi .  '" method="POST" name="auriga_checkout" id="auriga_checkout">' . "\n";
	foreach ($formfields as $field=>$value) {
		echo '<input type="hidden" name="' . $field . '" value="' . $value . '" />' . "\r\n";
	}
	echo '</form>';
?>
				
	<script type="text/javascript">
		var t = setTimeout('document.getElementById("auriga_checkout").submit()',500);
	</script>
</body></html>
