<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('tele2_subscription')->__('Offers') ?></h4>
    </div>
    <div id="offers_container" class="box">
        <div class="offers">
            <div id="offers_container_top"></div>
            <?php echo $this->getOffersBoxHtml(); ?>
        </div>
    </div>
</div>
