<!-- BEGIN ADFORM TRACKING -->
<script type="text/javascript" src="https://track.adform.net/serving/scripts/trackpoint/"></script>
<script type="text/javascript">
    <?php echo $this->getOrderTracking() . "\n"; ?>
    <?php echo $this->getTrackingIds() . "\n"; ?>
</script>
<noscript><p style="margin:0;padding:0;border:0;"><?php echo $this->getTrackingImg(); ?></p></noscript>
<!-- END ADFORM TRACKING -->
