<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>
        <?php echo $this->getChildHtml('header') ?>
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('breadcrumbsContainer') ?>
        <div class="wrapper-grey after-breadcrumbs">
            <div class="container web-shop">
                <div id="header_placeholder">
                    <?php echo $this->getChildHtml('header_section'); ?>
                </div><!-- #header-->
                <div id="middle_template3">

                    <div id="container_template3">
                        <div id="content_template3">
                            <?php echo $this->getChildHtml('content') ?>
                        </div><!-- #content-->
                    </div><!-- #container-->

                    

                </div><!-- #middle-->
                <div id="footer_placeholder">
                    <?php echo $this->getChildHtml('footer_section'); ?>
                </div><!-- #footer -->
            </div>
        </div>

        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>

<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>